<a href="https://colab.research.google.com/github/RJ2517/python-ml-projects/blob/main/MatrixOperationTool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def get_matrix():
    r = int(input("Enter number of rows: "))
    c = int(input("Enter number of columns: "))

    print("Enter matrix values row-wise (space separated):")
    matrix = []
    for i in range(r):
        row = list(map(float, input().split()))
        matrix.append(row)

    return np.array(matrix)

In [ ]:
print("====== MATRIX OPERATIONS TOOL ======")
print("1. Matrix Addition")
print("2. Matrix Subtraction")
print("3. Matrix Multiplication")
print("4. Matrix Transpose")
print("5. Determinant Calculation")

====== MATRIX OPERATIONS TOOL ======
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Matrix Transpose
5. Determinant Calculation


In [ ]:
choice = int(input("Select an operation (1-5): "))

Select an operation (1-5): 2


In [ ]:
if choice == 1:
    print("Enter Matrix A")
    A = get_matrix()
    print("Enter Matrix B")
    B = get_matrix()

    if A.shape == B.shape:
        print("Result (Addition):")
        print(A + B)
    else:
        print("Addition not possible. Dimensions mismatch.")

elif choice == 2:
    print("Enter Matrix A")
    A = get_matrix()
    print("Enter Matrix B")
    B = get_matrix()

    if A.shape == B.shape:
        print("Result (Subtraction):")
        print(A - B)
    else:
        print("Subtraction not possible. Dimensions mismatch.")

elif choice == 3:
    print("Enter Matrix A")
    A = get_matrix()
    print("Enter Matrix B")
    B = get_matrix()

    if A.shape[1] == B.shape[0]:
        print("Result (Multiplication):")
        print(np.dot(A, B))
    else:
        print("Multiplication not possible. Invalid dimensions.")

elif choice == 4:
    print("Enter Matrix")
    A = get_matrix()

    print("Result (Transpose):")
    print(A.T)

elif choice == 5:
    print("Enter Square Matrix")
    A = get_matrix()

    if A.shape[0] == A.shape[1]:
        print("Result (Determinant):")
        print(np.linalg.det(A))
    else:
        print("Determinant not possible. Matrix must be square.")

else:
    print("Invalid choice. Please select between 1 and 5.")


Enter Matrix A
Enter number of rows: 3
Enter number of columns: 3
Enter matrix values row-wise (space separated):
1 2 3
4 5 6
7 8 9
Enter Matrix B
Enter number of rows: 3
Enter number of columns: 3
Enter matrix values row-wise (space separated):
1 2 3
4 5 6
7 8 9
Result (Subtraction):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
